### ISSUE TITLE
Native Possible?

### ISSUE THREAD

**Issue by konsumer** [Dexus/pem#3]
I am unsure of how to go about it, but I think it would be neat if pem used `crypto` native functions, instead of openssl command-line stuff, especially for Windows or really bare cloud machine deployments. Do you think this is possible?

**Comment by andris9** [comment]
Node `crypto` is not much of a help in this case as it does not have appropriate functions, otherwise `pem` module wouldn't be even needed. It would be possible to create a C binding to openssl module and create the keys directly in node without spawning a command line process but I'm not really comfortable with the C stuff. I didn't want to solve the key generation issue this way but I didn't find anything simpler or quicker to implement, so I guess the module is going to stay as it is.

**Comment by konsumer** [comment]
I am working on a [ursa](https://github.com/Obvious/ursa)-based native version. Will update if I make progress.

**Comment by konsumer** [comment]
I am a bit stuck due to my lack of knowledge about TLS/SSL, I think.  [This](https://github.com/konsumer/pem/blob/master/lib/pem.js) is what I have.  `createPrivateKey()` works.  I am really not too sure if `createCSR()` is doing what it is supposed to be. Maybe [dcrypt](https://github.com/dekz/dcrypt) would be a good candidate for low-level stuff, instead of ursa, as it has `x509.createCert()` & `x509.signCert()`
