### ISSUE TITLE
v1.14.5 seems to have changes intended for v1.15.0

### ISSUE THREAD

**Issue by jmansor** [Dexus/pem#313]
Hi, I noticed v1.14.5 requires node v14.0.0 which seems to be like it was intended to be in v1.15.0 instead. Is this the case? Or am I reading the git history wrong?

Thanks in advance.

**Comment by Dexus** [comment]
Right, actually it should be 1.15.0, if the everything would have been ready so far. The next version 1.16 will be correct and 1.14.5 will be revoked/marked as deprecated.

Version 1.15.x will be skipped because of the buggy releases.

Unfortunately, it was a mistake, so I get version 1.16 only later ready, where I have checked some alleged errors.

Best Regards, Josef

**Comment by jmansor** [comment]
Sounds good, thanks for your response @Dexus.

**Comment by jerryfromearth** [comment]
Hi @Dexus , thanks for the quick response. Could you please revoke 1.14.5 from npm, as it's causing some headache for my project and it's not trivial to fix it from my side, due to nested dependencies and other reasons?
Thanks a lot.

**Comment by Dexus** [comment]
I marked `pem@1.14.5` as deprecated. It should not longer shown as latest release.

**Comment by jerryfromearth** [comment]
Hello @Dexus ,
I'm afraid the deprecation isn't doing what you wanted. Now `pem@1.14.5` is still shown as the latest, and the package still has `node: '>=14.0.0'` as the engine requirement, as can ben seen by e.g. `yarn info pem`.
Could you please take the code of `pem@1.14.4`, change its version to `1.14.6`, and publish it anew? I believe that's the proper way to fix it, and that will solve my problem. 
Thanks a lot.

**Comment by Dexus** [comment]
yarn take some time to update there data. no need to do this here.

**Comment by jerryfromearth** [comment]
@Dexus Sorry I don't understand. Do you mean after some time NPM will update their data and fix the "latest" tag so it points to `pem@1.14.4`?

**Comment by jerryfromearth** [comment]
I'm not sure the tool (yarn) matters here. `npm view pem` also shows `latest: 1.14.5` together with the deprecated note. And "npm install pem" would still install 1.14.5 instead of the good old 1.14.4.
Sorry if this is too much to ask, but could you please republish `pem@1.14.4` as `pem@1.14.6`?

**Comment by Dexus** [comment]
I pushed `pem@1.14.6` with the same result as `pem@1.14.4` hope you're happy now.

**Comment by jerryfromearth** [comment]
@Dexus You have no idea how happy I am :)

When you inevitably increase the node version requirement, please please consider increasing the major version instead of the minor version, because it's a breaking change for users like us that use `pem@^1.0.0` in the production code and are still stuck on node 12 for various reasons.
I'm in no way more knowledgeable in these things than you though, so it's your decision in the end and I'm just providing a suggestion.

Thanks for the effort and devotion you have put into these projects!

**Comment by sigv** [comment]
@Dexus, are there some setbacks for the ~~`pem@1.16.0`~~ `pem@2.0.0` release? We would like to have the OpenSSL 3 changes currently on `master` branch to be incorporated into a `latest` release tag.
