### ISSUE TITLE
OpenSSL v3 support

### ISSUE THREAD

**Issue by GnunuX** [Dexus/pem#316]
GNU/Linux distributions provides OpenSSL v3 command line is now.
If the work seems to be done on master, there is no stable version available.
Is a new release in the pipeline?

**Comment by Dexus** [comment]
Will have to look, when I get the time to finish and retest everything. Hope that I have next week some more time to work on it.

**Comment by jsjoeio** [comment]
It looks like this was added in https://github.com/Dexus/pem/commit/7ec825744b9cf1a9cab37983302fa6d7da8a9b22

But GitHub releases only has up to 1.14.4 and NPM has 1.14.6 but not 1.14.5 even though the `package.json` in the repo says 1.14.5. Any ideas on when this will make it into a release?

**Comment by sharper** [comment]
pem  readPkcs12  error on  ubuntu 22.04 LTS  OpenSSL 3.0
fixture such as:
https://github.com/jenkins-infra/release/commit/520e997f9c71c6ee77776c955331d1593380aad4

**Comment by eoin-mccarthy** [comment]
Is there a plan to put this fix into a release? When would this be available?

**Comment by robertsLando** [comment]
News on this?

**Comment by ponsfrilus** [comment]
Hello, we would be happy to have this released on npmjs :) Thanks!

**Comment by meriadec** [comment]
:wave: @GnunuX would it be possible to publish on npm? we would like to rely on the `-legacy` option being automatically set when needed, and that piece of code is not present on the actual latest npm package.

Thanks a lot!

**Comment by tkurki** [comment]
I am also seeing #346. Please give some indication if this is going to get fixed or not, so we can plan accordingly.

**Comment by yuriifedorchuk** [comment]
Using OpenSSL version `3.0.8`.
pem npm version `1.14.6`.

Using `createPrivateKey` method results in `RSA PRIVATE KEY not found from openssl output` error. 

Rolling back to pem `1.14.5` _**fixes the issue**_.

What is the problem with version `1.14.6`?

It seems to have obsolete codebase which is different from `master` branch.

**Comment by schoettler** [comment]
Having the same issue, temporally making ends meet with: https://community.postman.com/t/postman-ca-certificate-not-found-ubuntu-snap/30816/3

**Comment by robertsLando** [comment]
I just ended up switching to https://www.npmjs.com/package/selfsigned

**Comment by diegoholiveira** [comment]
I opened #351 and I think this PR will make it work fine with OpenSSL V3.

**Comment by robertsLando** [comment]
Giving tha activity of the author on this repo I don't think that PR will ever be merged/released

**Comment by Dexus** [comment]
@robertsLando It's OpenSource that I work on in my spare time - If I ever have free time, with the kids.... Since I get no support from outside, although many companies use the package commercially, I'm also not exactly 100% motivated.
However, I am happy when other users create PRs that I like to process and merge.

**Comment by robertsLando** [comment]
@Dexus Didn't want to be rude with my comment, it's just the reality of facts. AFAIK a fix for this has been merged long time ago but it was just missing a release for it otherwise I use to submit PR if/when I'm able to fix the issues.

> It's OpenSource that I work on in my spare time - If I ever have free time, with the kids....

I'm an OSS developer like you and I know what that means, but again giving your activity on this repo in last years I can say that if there will ever be other bugs/security issues them will likely not get fixed or at least not soon so I suggest considering alternatives 🙌🏼

**Comment by Dexus** [comment]
This should now fixed by release of 1.14.7 https://www.npmjs.com/package/pem/v/1.14.7 
Thanks to @diegoholiveira and @misi
